version: '3.7'

services:
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    bot:
        build: .
        command: python rubbergoddess.py
        depends_on:
            - db

volumes:
    postgres_data:
