name: Rubbergoddess

on:
  push:
    branches: [ master ]
    paths:
    - "**/*.py"
    - "**/*.json"
    - "**/*.yml"
  pull_request:
    branches: [ master ]
    paths:
    - "**/*.py"
    - "**/*.json"
    - "**/*.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-$${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}

    - name: Install black and flake8
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 flake8-black flake8-print

    - name: Check the code
      run: |
        # Run flake8 to find critical errors
        flake8 . --count --select=BLK,E9,F70,F82 --statistics

        # Run flake8 to find non-critical errors, while ignoring errors linked to black and our codestyle preferences
        flake8 . --count --exit-zero \
        --ignore=E12,E20,E221,E222,E241,E251,E266,E271,E272,E30,E722,W50 \
        --per-file-ignores="rubbergoddess.py:T001,F401 core/output.py:T001 cogs/errors.py:T001" \
        --exclude=config/* --max-complexity=13 --max-line-length=110 --statistics

        # Check the code with black
        black . --check --line-length=100
